name: Test
on:
  push:
    branches:
    - !master
jobs:
  release:
    runs-on: ubuntu-18.04
    steps:
    - name: Source checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Release
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Insert Go test & Build Here" ## Insert Go test & Build Here
        npx semantic-release